### ISSUE TITLE
Unable to find a converter for this representation : [*/*]

### ISSUE THREAD

**Issue by kugtong33** [restlet/restlet-framework-java#1033]
I am currently developing a simple file upload mechanism using `Restlet` and I am facing this error:

`2015-02-27 15:51:19,246 | WARN  | estlet-215390046 | FileApplication                  | 57 - org.restlet - 2.3.0.snapshot-v20141217-1648 | Unable to find a converter for this representation : [*/*]`

Restlet client:

```java
this.resource = new ClientResource("http://localhost:8090/FileService/Upload");
this.representation = new FileRepresentation(file, MediaType.ALL);
this.representation = resource.post(representation);
```
the file is an input of the function.

Restlet server:

```java
@Post
public JsonRepresentation represent(FileRepresentation request) {

        String filename = UUID.randomUUID().toString();

        File file = new File(filename);
        try (
            InputStream inputStream = request.getStream();
            FileOutputStream outputStream = new FileOutputStream(file)) {
            while ((streamByte = inputStream.read()) != -1) {
                outputStream.write(streamByte);
            }

            outputStream.flush();
            outputStream.close();
            inputStream.close();

            return new JsonRepresentation(
                new JSONObject()
                .put("filename", filename)
            );
        } catch (IOException | JSONException exception) {
            this.getResponse().setEntity(exception.getMessage(), MediaType.TEXT_PLAIN);
            throw new ResourceException(Status.SERVER_ERROR_INTERNAL, exception.getMessage());
        }
    }
```

I checked the Conventers by using:

```java
System.out.println("DEBUG::ENGINE_INFO::" + Engine.getInstance().getRegisteredConverters().toString());
```
Output:
`DEBUG::ENGINE_INFO::[org.restlet.ext.json.JsonConverter@64c41f55, org.restlet.engine.converter.DefaultConverter@728bf43c, org.restlet.engine.converter.StatusInfoHtmlConverter@4f3172b9]`

I am just trying to do the simplest mechanism for uploading a file (not multiple files).
Hope you guys can help me.

OS: Ubuntu 14.04
Environment: Apache Felix/Apache Karaf
Java: Oracle Java 8
Restlet Version: 2.3.0

**Comment by thboileau** [comment]
Hello,

I will give a little bit more details later, but there is no need to specify  "FileRepresentation" in the argument of the Java method:

```java
@Post
public JsonRepresentation represent(Representation request) {
}
```

In addition, I will use the `org.restlet.engine.io.IoUtils.copy(inputStream, outputStream)` method in order to effectively create the file on disk.
Just for the matter of example, I introduce you another version of your code that declares an exception class called `MyException` (in this case, it is located is an inner class, but it should in its own class. This exception is part of the contract of your method (in the `thrown` clause). This class holds a `Status` annotation that allows two things:
 - serialize the exception with its attribute (it may be your own)
 -  specify the status of the response

```java
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.UUID;

import org.json.JSONException;
import org.json.JSONObject;
import org.restlet.engine.io.IoUtils;
import org.restlet.representation.Representation;
import org.restlet.resource.Post;
import org.restlet.resource.ServerResource;
import org.restlet.resource.Status;

public class UploadServerResource extends ServerResource {

    @Status(value = 500)
    private static class MyException extends Exception {
        private static final long serialVersionUID = 1L;
        public MyException(String message) {
            super(message);
        }
    }

    @Post
    public JSONObject represent(Representation request) throws MyException {

        String filename = UUID.randomUUID().toString();

        File file = new File(filename);
        try (InputStream inputStream = request.getStream();
                FileOutputStream outputStream = new FileOutputStream(file)) {
            IoUtils.copy(inputStream, outputStream);

            outputStream.flush();
            outputStream.close();
            inputStream.close();

            return new JSONObject().put("filename", filename);
        } catch (IOException | JSONException  e) {
            throw new MyException(e.getMessage());
        }
    }
```

**Comment by kugtong33** [comment]
Yes, that one solved the problem! :+1:  Thanks

But it is just an alternative right?, I mean when I use

```java
@Post
public JsonRepresentation represent(JsonRepresentation request){

}
```
for `JSON` requests, there is no problem converting the request.

**Comment by thboileau** [comment]
Actually, conversion from Representation to JsonRepresentation is taken into account by the JsonConverter supplied by the org.restlet.ext.json extension.
There is no converter that support the conversion from Representation to FileRepresentation which leads the framework to log: `Unable to find a converter for this representation : [*/*]`.

Just in order to give more details.
As a developer, you set up an annotated Java method with the following signature:
```java
 public ClassA myMethod(ClassB object) {
  }
```
In this case, the framework tries to answer the following question: How can I convert an input Representation (read from the socket) to an instance of ClassB?
The current algorithm is the following:
 - if ClassB is already Representation, no conversion applies
 - otherwise, loop over each available converters (including the default one, called DefaultConverter), and ask them if they are able to convert Representation to ClassB.
 - once a converter has been chosen, applies the conversion.

 This page list all available converters and the conversion supported: http://restlet.com/technical-resources/restlet-framework/guide/2.3/core/services/converter
