### ISSUE TITLE
Restlet JAX-RS encoding problem - CRITICAL.

### ISSUE THREAD

**Issue by theprivateland** [restlet/restlet-framework-java#1038]
Guys Im testing migration from jersey and have tested few frameworks with angle of smooth workflow.

Restlet is a winner - most flexible, doesn't do any oddity with memory and server shuts down nicely.

However, embarasingly, its has seriosuly annoying bug:
```
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern [...]

```

It tries to double encode request parameters (I think its form parameters case or query) when used with standard jax-rs services.

None of other libraries has this problem. 

Is there a way it can be fixed any time soon? It is something it's been reported at 2.09 version... very annoying. 

I wish I can use Restlet but this bug is a deal breaker.

I know @Encode will stop decoding the parameter, but I need to decode it from url encoding...

**Comment by thboileau** [comment]
Hi @theprivateland , do you have any test case?

**Comment by peterfronc** [comment]
Thanks for reply, I was forced to use other jax-rs implementation (rest easy from jboss).
The problem was observed while using 
@FormParam
Create any standard jax-rs service.
Map the service in web.xml (standard servlet way).
Just send encoded message containing % characters.

This issue occured in past from what I could google, just review encoding steps in framework and ensure its not happening twice (or maybe catch the exception as its not catched - it gets through to filter).

Its small but bug bug that makes migration practically impossible. I like the flexibility and standard resource api as opposite to jax-rs, but I cant afford now to rewrite old services (and annotating with @Encode all forms is a bit overhead).

**Comment by thboileau** [comment]
I'm not so happy to have fixed this so easy bug, just now.

**Comment by peterfronc** [comment]
So its fixed? Release version?

**Comment by jlouvel** [comment]
@peterfronc Thierry made the fix in branch 2.3, so it will be part of version 2.3.2:
https://github.com/restlet/restlet-framework-java/commit/c60c99b70812868301e90b08582207e16d2cd05e?diff=unified

@thboileau Can we fix it as well on "master" branch? I'm reopening to make sure we don't miss this.

**Comment by peterfronc** [comment]
Awesome, Ill prepare soon to remove resteasy (very happy).

**Comment by jlouvel** [comment]
@peterfronc Happy to help you. BTW, could you describe how Restlet JAX-RS implementation compares with RESTeasy in your project context?

**Comment by peterfronc** [comment]
Sorry for late reply, been busy recently.
Restlet is easier to setup and has it better explained, big advantage is also size and speed (not to mention its easy to run it standalone, without web container). Personally I use JAX-RS as Im lazy to rewrite old code, best approach is OO oriented - this is why I am happy to see bugfix. RESTEasy ain't bad... its just big and more complex to configure.

**Comment by jlouvel** [comment]
Thanks @peterfronc for the valuable insights.

**Comment by thboileau** [comment]
I plan to release 2.3.2 this friday, and refresh 3.0 branch this week also.

**Comment by peterfronc** [comment]
Thanks a lot! Looking forward to it.

**Comment by thboileau** [comment]
Branch 3.0 refreshed. closing.
