### ISSUE TITLE
Unprocessable Entity error when accessing ServerResource (XStream used not Jackson)

### ISSUE THREAD

**Issue by kerbymart** [restlet/restlet-framework-java#1042]
The error happens when GWT app is accessing a Restlet ServerResource using ClientResource it throws "Unprocessable Entity" 

This may be due to the different way XStream generates JSON, this is the format:

``` json
{ "stuff" : { "prop1" : "value", "prop-2": "value" } }
```

Which GWT ClientResource is generating a different form of JSON String, thus the content type is OK but the format is malformed causing XStream to throw "Unprocessable Entity"

**Comment by thboileau** [comment]
Hi @kerbymart , if I understand well, you are sending from a GWT application some JSON payload, which is then serialized by the XStream converter.
I guess you are using the Json extension for the GWT edition in order to achieve this task. As this extension leverages the json API (`com.google.gwt.json.client` package) it should give you a full control of the payload. Do you see the generated payload (for example, you can activate the developer console in your browser)?

**Comment by kerbymart** [comment]
@thboileau Yes I can see the payload now in the browser (but just after applying a fix), here: 

http://www.pastekit.com/lWAg6

**Comment by thboileau** [comment]
Hi @kerbymart 
after the fix, do you still have the issue?
Having said that, I'm not able to read the content of the pastekit.com page (the page is unresponsive). Do you mind, pasting the text in a comment?

**Comment by thboileau** [comment]
since xstream extension has been dropped, let's remove this ticket.
