### ISSUE TITLE
Getting ResourceException messages without <html> tags

### ISSUE THREAD

**Issue by kugtong33** [restlet/restlet-framework-java#1115]
We are getting resource exceptions by using `setEntity()` in the `Resource` like this

``` java
try {
    /* Do something meaningful */
    return new JsonRepresentation(response);
} catch (SQLException | JSONException exception) {
    this.getResponse().setEntity(exception.getMessage(), MediaType.TEXT_PLAIN);
    throw new ResourceException(Status.SERVER_ERROR_INTERNAL, exception.getMessage());
}
```

Then in our `Restlet Client` we get the messages by using `getEntity()`

``` java
try {
    /* Do something using POST or GET */
} catch (ResourceException exception) {
    try {
        throw new ResourceException(
            exception.getStatus(),
            this.resource.getResponse().getEntity().getText()
        );
    } catch (IOException ex) {
        throw new ResourceException(Status.CLIENT_ERROR_BAD_REQUEST, ex.getMessage());
    }
}
```

To notify the exception message we get it like this

``` java
try{
    /* Do service request using the restlet client */
} catch (ResourceException exception) {
    Notification.getInstance().notify(exception.getStatus().getDescription());
}
```

In the previous releases, `2.1.x` this was working right but when we upgraded to `2.3.x` it didn't work right.

How can I remove the `<html>` tags when getting exception messages or are there any API change that I missed?

**Comment by kugtong33** [comment]
@thboileau , If this gets fixed would it be in the next latest version then?
Or where would be the right place to know this?

**Comment by thboileau** [comment]
Hello @kugtong33 ,

I'm really sorry for the delay of my reponse. I's hard to me to dedicate time as I want.
I send you a sample project that illustrates the way to handle exception in your code using Restlet Framework 2.3.7.

**First: on client side.**
You can directly access the response's entity thanks to the ResourceException:
```java
        try {
            new ClientResource("http://localhost:8182/resource").get();
        } catch (ResourceException exception) {
            System.out.println(exception.getResponse().getEntityAsText());
        }
```

**Then: on server side.**
By default, exceptions (even ResourceException) are bean that are now serialized (in HTML for example). By doing so, you can think an Exception is a bean as any other bean.
In addition, using your own StatusService, you can fully control how your compute the representation linked to an exception.

the first step is to update your server resource code in order to directly throw exception:

```java
public class MyServerResource extends ServerResource{
    
    @Get
    public String fail() throws MyException {
        throw new MyException("This bean will be serialized according to user's media type preferences and converters present in your application");
    }
}
``` 

Then, in your Status Service, you can, for example, compute the a simple text representation for specific kind of exceptions:

```java

public class MyStatusService extends StatusService {

    @Override
    public Representation toRepresentation(Status status, Resource resource) {
        if (status.getThrowable() instanceof MyException2) {
           // return the message as a simple text representation
            return new StringRepresentation(status.getThrowable().getMessage());
        }
        return super.toRepresentation(status, resource);
    }
}
```

[test-rf-exceptions.zip](https://github.com/restlet/restlet-framework-java/files/245425/test-rf-exceptions.zip)

**Comment by thboileau** [comment]
By doing so, it should simplify your code. What do you think about that?

**Comment by kugtong33** [comment]
@thboileau , hello thanks for all the help, I think this is now closed, I've been doing node projects now and more than a year of not doing any restlet based projects :)
