### ISSUE TITLE
Is there a way to override HtmlConverter

### ISSUE THREAD

**Issue by talmdal** [restlet/restlet-framework-java#1201]
If I get an error status returned (i.e. on my rest request) the content is usually an html page.  I'm assuming that this is the HtmlConverter making this happen.  Is there away to return the status as a json content type? i.e. {"code": 999, "reason": "...."}

Thanks
Tim

**Comment by thboileau** [comment]
Hi @talmdal,

actually, the [StatusService](https://restlet.com/technical-resources/restlet-framework/guide/2.3/core/services/status) is in charge of converting error statuses/exceptions into representations.
Here are a few words about its behavior (in 2.3 version). There are two steps:
* computing the object that will the source of data in order to generate the final representation
* according to client media type preferences (set in the `accept` header), look for the more adapted converter (could be `HtmlConverter` in case of browser).

So, If you are using 2.3 version, and if your application leverages the Jackson extension, for example, you should be able to obtain a `json` version of the error status.

As a side note, you can customize the representation of error status by using `@status` annotation.
```java
@Status(400)
public class MyException extends Exception {

    String message;

    public MyException() {
    }

    public MyException(String message) {
        setMessage(message);
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}
```
This exception will be serialized as a simple bean, and set the response's to 400.

Just throw it in your ServerResource:
```java
@Get
public void justFails() throws MyException {
    throw new MyException("this is an error");
}
```

**Comment by talmdal** [comment]
Outstanding... thanks for the response, that was very helpful
