### ISSUE TITLE
Why did you design Resource instances to be created per-request?

### ISSUE THREAD

**Issue by greenfrog82** [restlet/restlet-framework-java#1305]
Hi all ~
I like to think about software architecture. So using restlet, I've studied architecture of restlet.
And I have some question.
Why did you design Resource instances to be created per-request?
Resource instance created by singleton is more performance than Resource instance created by per-request. also so far as I know, finder of restlet create instance by reflection, it is very harmful for performance. 
If you design Resource instance created by singleton, then you maybe need to synchronized to mange singleton instance. Maybe is synchronize more harmful than reflection? So did you design Resource instances to be created per-request?

I'm very wondering about it.
please answer anyone.
Thank you for your reading!!

**Comment by Tembrel** [comment]
On Mon, Jan 8, 2018 at 11:41 AM, greenfrog <notifications@github.com> wrote:

> Resource instance created by singleton is more performance than Resource
> instance created by per-request. also so far as I know, finder of restlet
> create instance by reflection, it is very harmful for performance.
>
On the contrary, object creation, even reflective creation, is very
inexpensive in Java, especially when compared to the cost of handling a
network request. See, for example, this question and its answers
<https://softwareengineering.stackexchange.com/questions/149563/should-we-avoid-object-creation-in-java>
for details. (That thread is over five years old, but object creation has
only become *faster* since then.)

Think of the resource instance as the state of handling one request, where
there might be thousands of requests being handled at the same time. Since
that state can be different for each request, you can't have a singleton to
hold this state.


> If you design Resource instance created by singleton, then you maybe need
> to synchronized to mange singleton instance. Maybe is synchronize more
> harmful than reflection? So did you design Resource instances to be created
> per-request?
>
First of all, Restlet *does* have "singleton" classes that are re-used by
multiple requests: the Restlet class! A typical Restlet program builds a
graph of Restlet instances at initialization time for routing and
transforming requests and responses and creating the resource instances.
Those Restlet instances do not carry per-request information. They have to
be designed carefully so that they can be shared by multiple requests
simultaneously.

And it's *extremely* difficult to design thread-safe classes.
Over-synchronization can lead to liveness failures and
under-synchronization can lead to safety problems.

Resource classes (subclasses of ServerResource, that is) need *not* be
thread-safe, so they are much easier to write. This is critical for Restlet
application developers to be able to write their own resource classes. It
is Restlet Framework's job to make sure to make sure that resource
instances and their fields aren't shared unsafely between threads. (It's
not easy to get this right in all settings, but at least it's not up to the
Restlet user.)

--tim

**Comment by greenfrog82** [comment]
Thank you for your answer.
I agree your comment and reference links. 
I recognize the reason why you've designed restlet framework like this.
