### ISSUE TITLE
Update jetty dependency

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#1326]
Restlet's Jetty extension currently depends on jetty 9.3.21.v20170918 which is known to be affected by the following vulnerability:

- CVE-2017-9735

Upgrade to Jetty 9.4.11.v20180605

**Comment by 01es** [comment]
@thboileau version 2.4.0 of `org.restlet.ext.jetty` still has dependencies to various `org.eclipse.jetty` libs versioned `2.3.21.x`.

![image](https://user-images.githubusercontent.com/5511940/48876951-19f64180-ee55-11e8-849e-0171d72487a6.png)

When upgrading to Jetty 9.4.x I have excluded transitive 9.3.x dependencies explicitly in the project POM. Considering that this issue is closed, could you please advise what is the reason for the 9.3.x dependencies to be still present. Thank you.
