### ISSUE TITLE
Restlet Jaxrs Extension is deprecated why?? will it be removed or replaced by something else?

### ISSUE THREAD

**Issue by Kastin-berlake** [restlet/restlet-framework-java#1378]
hello !

I am a loyal user of restlet . our project has always used the jaxrs module to support the jax-rs .However, it is obsolete in 2.4.3 and will be removed in 2.5. 
Why remove it? Will restlet continue to support jax-rs ? Do I need to use jersey or CXF as a replacement?

**Comment by cyberquarks** [comment]
@Kastin-berlake you may be interested on joining https://gitter.im/restlet-framework/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by jlouvel** [comment]
Hi @Kastin-berlake The JAX-RS extension was contributed many years ago but the initial contributor didn't actively maintain. As JAX-RS spec evolve, the Restlet-based implementation couldn't keep up with it, so rather than keep an obsolete extension will low maintenance, we decided to deprecate it and eventually remove it in 2.5. 

The added value compared to Jersey or RESTeasy or CXF is rather low as well, so the recommendation is to switch to one of those projects is JAX-RS API is really required.
