### ISSUE TITLE
Question about 2.5 new_build and GWT

### ISSUE THREAD

**Issue by sblommers** [restlet/restlet-framework-java#1413]
Hi there! 

I see that 2.5 newbuild has a mavenized build :raised_hands: : . I pulled the branch and split restlet into 2 parts projects, org.restlet and org.restlet.gwt and use it succesfully with gwt 2.11.0 (with jakarta.*) on java 21. I did notice that **org.restlet.ext.gwt** extension dissappeared, I currently use the 2.5-M(5) (5 is my custom build) version and exclude dependencies to get things working again. 

I was wondering why org.restlet.ext.gwt was removed. 
Is the gwt version going to be removed also? I sure hope not.
If it is going to be maintained how should maven build the gwt edition, classifier?

Thanks you for the new build :+1:

**Comment by thboileau** [comment]
Hi @sblommers 
thanks for your remark. We are currently thinking about our first decision, and are considering to step back.
Meaning, at least the org.restlet.ext.gwt extension will be back into 2.5 version.

> If it is going to be maintained how should maven build the gwt edition, classifier?

We are thinking about it.
If we keep it, we need to prevent package names collision (think of "Request" class located in the same package "org.restlet" in "jse" or "gwt" editions). We could have a distinct repository, or have a new module (but with different package name like org.restlet.gwt instead of org.restlet).

**Comment by jlouvel** [comment]
The updated 2,5 branch, soon to be release as 2.,5 M2 is now fully mavenified and has a separate GWT edition included with its own code base,
