### ISSUE TITLE
Add Java ME editions of Restlet

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#179]
Initial ticket : http://restlet.tigris.org/issues/show_bug.cgi?id=917

**Comment by thboileau** [comment]
@jlouvel 
I wonder if this ticket is still relevant for the framework

**Comment by Tembrel** [comment]
No resources should be put into creating a Java ME Restlet edition.

The success of Android and the introduction of modules with Java 9 have essentially relegated Java ME to legacy status. Yes, there are plenty of devices still out there that use it, but any development work still being done is almost certainly for maintenance purposes. Note that there have been [no Java ME JSRs since 2014](https://en.wikipedia.org/wiki/Java_Platform,_Micro_Edition#JSRs_(Java_Specification_Requests)).

**Comment by thboileau** [comment]
sure @Tembrel , you're totally right.

let's close the ticket
