### ISSUE TITLE
Upgrade Spring Framework to version 4

### ISSUE THREAD

**Issue by jlouvel** [restlet/restlet-framework-java#859]

**Comment by fieder** [comment]
Hi, is this going to be done any time soon? Certain components like Spring data Mongo have changed quite a lot and the stable and decent JDBC version for Mongo 3.x requires Spring 4.x. Other components in our stack such as WebSockets also require Spring 4.x. Maintaining coexistence is proving to be extremely painful between Spring 3.x and the rest of the stack. The only reason why we can't upgrade to Spring 4 is RestLet :-/  I wander if it's time to move the REST controller to Spring instead...otherwise we are stuck in the past and we can't move on. Please let us know what you think.

**Comment by jlouvel** [comment]
@fieder Thanks a lot for the feed-back. Could you detail what would be necessary from your point of view for Restlet Fwk to be compatible with Spring v4?

I'm adding our Spring expert @templth here so he could help discussing this upgrade.

**Comment by fieder** [comment]
@jlouvel no worries. Hi @templth!  This is [our product](https://havefunhub.com). Our main API is a Spring 4 4.1.8.RELEASE web app that exposes a REST and WebSockets API which uses Spring Security 4.0.1.RELEASE (Spring Social + JWT custom solution for auth). Data layer access is standardised in our stack through Spring Data. There is another API we did back in 2010 that is Restlet based (basic auth). To mention a particular example, we use spring-data-mongodb 1.8.0.RELEASE and there is no way to make it coexist with the old module Restlet which is still serving a portion of our API. I switched off MongoDb access in the Restlet web app to avoid conflicts but I lost functionality that relies on that. As we move the other web app further on more limitations arise. Having Spring 4.x will ease the way forward as we develop new stuff. What's your view?

**Comment by fieder** [comment]
@jlouvel @templth any update?

**Comment by thboileau** [comment]
Hello @fieder , thank you for keep the ticket alive.
We try to free some time to help you.

**Comment by fieder** [comment]
@thboileau thank you. Do you need anything else from our side? How likely is this to be fixed? I don't want to come across as pushy at all but I need to make few decisions so appreciate your honesty.

**Comment by jlouvel** [comment]
Closing this one as Spring 5.3 is now supported by version 2.5 RC1.
