### ISSUE TITLE
Swagger support for the Google App Engine (GAE)?

### ISSUE THREAD

**Issue by edouardmercier** [restlet/restlet-framework-java#945]
Hello.

First of all, congratulations for the good job on Restlet, and the new support for Swagger.

I've been trying to play with this new extension (`org.restlet.gae:org.restlet.ext.swagger`) through Restlet `v2.3-SNAPSHOT`. Here is a feedback regarding issues that I've been facing:
1. the POM references the `javax.ws.rs:javax.ws.rs-api:2.0.0` which does not exist ; the one existing seems to be `javax.ws.rs:javax.ws.rs-api:2.0`: this makes the compilation tedious, and my work-around was to add directly the `javax.ws.rs:javax.ws.rs-api:2.0` artefact directly in my project POM ;
2. the POM references the `org.restlet.gae:org.restlet.lib.org.restlet.lib.org.eclipse.e4.core.contexts:jar:${lib-e4-version}` artefact: the `lib-e4-version` property does not seem to be defined, which causes a compilation issue. My work-around was to use the Maven `-Dlib-e4-version=0.12.RC1` command-line option ;
3. the document at http://restlet.com/learn/guide/2.3/extensions/swagger seems out-dated compared to the latest version of the source-code ;
4. I tried to declare a "SwaggerApplication" in my project, and ran it on a GAE development server and got the following exception stack trace:

```
[INFO] Avertissement: Exception or error caught by status service
[INFO] java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.reflect.generics.reflectiveObjects")
[INFO]  at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
[INFO]  at java.security.AccessController.checkPermission(AccessController.java:559)
[INFO]  at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
[INFO]  at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:429)
[INFO]  at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1529)
[INFO]  at java.lang.Class.checkPackageAccess(Class.java:2265)
[INFO]  at java.lang.Class.checkMemberAccess(Class.java:2245)
[INFO]  at java.lang.Class.getDeclaredFields(Class.java:1805)
[INFO]  at org.restlet.ext.swagger.internal.reflect.ReflectUtils.getAllDeclaredFields(ReflectUtils.java:59)
[INFO]  at org.restlet.ext.swagger.internal.info.RepresentationInfo.introspect(RepresentationInfo.java:117)
[INFO]  at org.restlet.ext.swagger.internal.reflect.Introspector.toDefinition(Introspector.java:682)
[INFO]  at org.restlet.ext.swagger.internal.reflect.Introspector.<init>(Introspector.java:841)
[INFO]  at org.restlet.ext.swagger.internal.reflect.Introspector.<init>(Introspector.java:828)
[INFO]  at org.restlet.ext.swagger.SwaggerSpecificationRestlet.getDefinition(SwaggerSpecificationRestlet.java:169)
[INFO]  at org.restlet.ext.swagger.SwaggerSpecificationRestlet.getResourceListing(SwaggerSpecificationRestlet.java:201)
[INFO]  at org.restlet.ext.swagger.SwaggerSpecificationRestlet.handle(SwaggerSpecificationRestlet.java:243)
```

Update: this exception occurs with the `class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl` argument on line 59 of the `ReflectUtils` class. I've trying to understand why this happens…

It seems that the Restlet Swagger `ReflectUtils` class uses an introspection which is not compliant with Google App Engine. I'm surprised because I actually use the GAE flavor of Restlet, hence is this due to the fact that I run the code in a GAE development server? Could you confirm that this Restlet Swagger extension is supposed to be compliant with the GAE, please? If yes, do you also intend to support the `JaxRsApplication` restlets?

Thank you for your time and support. Regards,

Édouard

**Comment by komasoftware** [comment]
Any ideas on how to move this forward ?

**Comment by thboileau** [comment]
Curiously, I've made a test using directly this method in a gae application, it worked for me.
I have to spend more time.

**Comment by komasoftware** [comment]
@thboileau my guess is that it depends on the complexity class structure of the incoming representation or return representation. These are the classes that will be introspected, not ?
The failing call is RepresentationInfo.introspect.
If you are sending/returning just a StringRepresentation, you might be lucky.

**Comment by thboileau** [comment]
I've made a test using a hand coded project exported to GAE. There is the code to the server resource.

```java
package org.thboileau.test;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.restlet.data.Parameter;
import org.restlet.resource.Get;
import org.restlet.resource.ServerResource;

public class HelloResource extends ServerResource {

	public static class Parameters extends ArrayList<Parameter> {

	}

	@SuppressWarnings("rawtypes")
	public static Field[] getAllDeclaredFields(Class type) {
		List<Field> fields = new ArrayList<Field>();
		Class currentType = type;

		while (currentType != null) {
			Field[] currentFields = currentType.getDeclaredFields();
			Collections.addAll(fields, currentFields);
			currentType = currentType.getSuperclass();
			if (currentType != null && currentType.equals(Object.class)) {
				currentType = null;
			}
		}

		return fields.toArray(new Field[fields.size()]);
	}

	@Get
	public String hello() throws ClassNotFoundException {
		StringBuilder sb = new StringBuilder();
		trace(sb, "HelloResource", HelloResource.class);
		trace(sb, "Parameters", Parameters.class);
		trace(sb, "ArrayList", ArrayList.class);
		trace(sb, "HelloResourcebis", "org.thboileau.test.HelloResource");
		trace(sb, "ParameterizedTypeImpl",
				"sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl");

		return sb.toString();
	}

	private void trace(StringBuilder sb, String name, Class<?> clazz) {
		sb.append(name).append(" ").append(clazz).append("\n");
		try {
			Field[] fields = getAllDeclaredFields(clazz);
			for (Field field : fields) {
				sb.append("  - ").append(field.getName()).append("\n");
			}
		} catch (Exception e) {
			e.printStackTrace();
			sb.append("  - cannot get fields due to: ").append(e.getMessage());
		}
		sb.append("\n");
	}

	private void trace(StringBuilder sb, String name, String classname) {
		try {
			trace(sb, classname, Class.forName(classname));
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
			sb.append(name).append("\n");
			sb.append("  - cannot get the class due to: ").append(
					e.getMessage());
		}
	}
}
```

**Comment by thboileau** [comment]
@edouardmercier, I wonder if this may be due to the version of GAE JDK. Could you try again using the 1.9.15 jdk?

**Comment by komasoftware** [comment]
I have tried your code, slightly modified to fit into my project. This is what I am getting :

```class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl\n  - cannot get fields due to: access denied (\"java.lang.RuntimePermission\" \"accessClassInPackage.sun.reflect.generics.reflectiveObjects\")```


```java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.reflect.generics.reflectiveObjects")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
	at java.security.AccessController.checkPermission(AccessController.java:559)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:429)
	at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1525)
	at java.lang.Class.checkPackageAccess(Class.java:2309)
	at java.lang.Class.checkMemberAccess(Class.java:2289)
	at java.lang.Class.getDeclaredFields(Class.java:1810)
	at com.klawt.server.resources.impl.HelloResource.getAllDeclaredFields(HelloResource.java:24)
	at com.klawt.server.resources.impl.HelloResource.trace(HelloResource.java:61)
	at com.klawt.server.resources.impl.HelloResource.trace(HelloResource.java:84)
	at com.klawt.server.resources.impl.HelloResource.hello(HelloResource.java:43)
```

**Comment by komasoftware** [comment]
AFAIK, this is not a new or recent restriction, it has always been there, cfr the JRE white list over here https://cloud.google.com/appengine/docs/java/jrewhitelist

IMO, there is no way around this restriction.

But I am not very familiar with Swagger, but this introspection process must be a one-time operation since your class structures won't change once your app is deployed.

So I am coming back to my previous suggestion of doing the introspection offline using a standard JVM before deploying and writing the results away in text files which can be deployed together with the app. The deployed app can then read out these files and generate the swagger-ui.

Unless there is a way around implementing the functionality without calling ```java.lang.Class.getDeclaredFields```, but I doubt that.

**Comment by komasoftware** [comment]
with JSON as response : 

HelloResource class com.klawt.server.resources.impl.HelloResource
  - annotated
  - conditional
  - existing
  - negotiated
  - variants
  - application
  - context
  - request
  - response

Parameters class com.klawt.server.resources.impl.HelloResource$Parameters
  - serialVersionUID
  - DEFAULT_CAPACITY
  - EMPTY_ELEMENTDATA
  - elementData
  - size
  - MAX_ARRAY_SIZE
  - modCount
  - MAX_ARRAY_SIZE

ArrayList class java.util.ArrayList
  - serialVersionUID
  - DEFAULT_CAPACITY
  - EMPTY_ELEMENTDATA
  - elementData
  - size
  - MAX_ARRAY_SIZE
  - modCount
  - MAX_ARRAY_SIZE

com.klawt.server.resources.impl.HelloResource class com.klawt.server.resources.impl.HelloResource
  - annotated
  - conditional
  - existing
  - negotiated
  - variants
  - application
  - context
  - request
  - response

sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl
  - cannot get fields due to: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.reflect.generics.reflectiveObjects") for class class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl

What strikes me is that it does return the declared fields for your own classes. The problem when requesting the declared fields for a class in package sun.reflect.generics.

So maybe it is sufficient to prevent introspection on these packages ?

**Comment by thboileau** [comment]
Hi Koen,

I get this trace:
```
HelloResource class org.thboileau.test.HelloResource
  - annotated
  - conditional
  - description
  - existing
  - name
  - negotiated
  - variants
  - application
  - context
  - request
  - response

Parameters class org.thboileau.test.HelloResource$Parameters
  - serialVersionUID
  - elementData
  - size
  - MAX_ARRAY_SIZE
  - modCount
  - MAX_ARRAY_SIZE

ArrayList class java.util.ArrayList
  - serialVersionUID
  - elementData
  - size
  - MAX_ARRAY_SIZE
  - modCount
  - MAX_ARRAY_SIZE

org.thboileau.test.HelloResource class org.thboileau.test.HelloResource
  - annotated
  - conditional
  - description
  - existing
  - name
  - negotiated
  - variants
  - application
  - context
  - request
  - response

sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl class com.google.apphosting.runtime.security.shared.stub.sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl
```

**Comment by komasoftware** [comment]
- sure that you are running on the GAE devserver ? 
 - Do you see the ```com.google.appengine.tools.development.DevAppEngineWebAppContext``` in the call stack when you break ?

I have the HelloResource attached to the router of a Application that is started from the web.xml. Then I start the GAE devserver.

**Comment by thboileau** [comment]
ah, I've just tried by deploying to the GAE environment, not in the local development server. Let me check.

**Comment by komasoftware** [comment]
bumping this again ...

**Comment by komasoftware** [comment]
Hi 

I have been digging a bit more into this. Commenting out most of my API, I managed to get a basic Swagger Application running.
This is what is now returned from the /api-docs call : 

```{"apis":[{"path":"/{customerid}"}],"apiVersion":"1.0","info":{"description":"","title":"com.klawt.server.ApplicationBootLoader@4dad108d"},"swaggerVersion":"1.2"}```

I am now trying to add this to the swagger UI app ```http://petstore.swagger.wordnik.com/``` but CORS is not enabled for the ```SwaggerSpecificationRestlet```.  So I am seeing this in the chrome console : 

```XMLHttpRequest cannot load http://localhost:8888/app/docs. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://petstore.swagger.wordnik.com' is therefore not allowed access.
swagger.js:14 Unable to Load SwaggerUI```



It is difficult to fit the CorsFilter in between by overriding since I don't have access to the private variable ```documented```in ```SwaggerApplication```. 

Any advice ?

**Comment by thboileau** [comment]
Hi @komasoftware , I'm able to spend some time today.

**Comment by thboileau** [comment]
Hi @komasoftware,

you can just add the CorsService to your application, for example in the constructor of your application:

```java
	public MyApplication() {
		super();
		getServices().add(new CorsService());
	}
```
If you leverage an authenticator, the first `options` request may be filtered and interrupted by the guard. In this case, you can call the `setSkippingResourceForCorsOptions` method.

**Comment by komasoftware** [comment]
Hi Thiery,

Back at this. Some API can be declared without problems, even for complex objects. 
The problematic case is where the result of my API is a generic Class :

```
public class SearchResult<D extends DomainResource> {

	protected int startIndex = 0;

	protected int pageSize = 15;

	protected String nextCursor = null;

	protected List<D> list = new ArrayList<D>();
	
	protected String orderBy = null;

        ... getters and setters...
}
```

Describing the generics seem to lead to call to :

```RepresentationInfo.introspect(Class<> clazz, MediaType mediaType)```

with value for clazz = ```sun.reflect.generics.reflectiveObjects```

which in turn leads to :

```access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.reflect.generics.reflectiveObjects")```

**Comment by komasoftware** [comment]
adding packages starting with ``"sun."`` or ``"sun.reflect."`` in the call to 
```
public static boolean isJdkClass(Class<?> clazz)
```
is enough to fix it ?

**Comment by komasoftware** [comment]
I have been trying to rebuild the editions after making changes to ReflectUtils in the apispark internal package. My change was to exclude the "sun.*" packages from introspection but the unit tests fail after this change. I'd appreciate some help moving forward from here :
``1
Setting up test org.restlet.test.service.StatusServiceTestCase#testRepresentation
------------- ---------------- ---------------

Testcase: testStrict took 0.02 sec
Testcase: testStrict took 0.011 sec
Testcase: testRepresentation took 0.389 sec
        FAILED
expected:<{"code":400,"[reasonPhrase":"Bad Request","description":"The request could not be understood by the server due to malformed syntax]"}> but was:<{"code":400,"[description":"The request could not be understood by the server due to malformed syntax","reasonPhrase":"Bad Request]"}>
junit.framework.ComparisonFailure: expected:<{"code":400,"[reasonPhrase":"Bad Request","description":"The request could not be understood by the server due to malformed syntax]"}> but was:<{"code":400,"[description":"The request could not be understood by the server due to malformed syntax","reasonPhrase":"Bad Request]"}>
```

**Comment by komasoftware** [comment]
I pulled everything in from 2.3.1 release and I cannot pass the tests. The test failure was not introduced by me. But it does stop me from continuing my investigations.

```
Testcase: testPetstoreSwaggerUrlToRwadef took 0.777 sec
        Caused an ERROR
null
java.lang.NullPointerException
        at org.restlet.ext.apispark.internal.conversion.swagger.v1_2.SwaggerUtils.getDefinition(SwaggerUtils.java:98)
        at org.restlet.test.ext.apispark.conversion.swagger.v1_2.SwaggerTranslatorTestCase.testPetstoreSwaggerUrlToRwadef(SwaggerTranslatorTestCase.java:361)
```

**Comment by edouardmercier** [comment]
I've re-attempted to have Swagger working on the GAE edition of Restlet v2.3.1, and went a step further, thank you for having fixed things.

However, I realize that most Swagger annotations are not taken into account, and I was wondering why. In addition (it must be something related to Swagger UI), when attempting to run web services through Swagger UI, the `example.com` domain is requested instead of the real implementation. The example projet (the hyperlink of which is broken) is really thin in terms of annotation, and I really find it hard to understand the logic behind. I know, that it takes a lot of time to write documentation, but I think that a deeper focus on Swagger with an example full of annotations would be great.

In addition, the promise is that Restlet should also be working with JAX-RS, but could not find a way to have it working, and could not find any example which shows how to plug Swagger in that case.

I am aware that my request is very demanding, but would you have some more material, so that we better understand how Restlet manages to be compliant with Swagger, to what extent, what are the known limitations, the roadmap, all that illustrated by a rich example.

Thank you for your attention and support.

**Comment by jlouvel** [comment]
Thanks Edouard for your interest in making this feature work properly, sorry it takes so long. I've adked to our team to have a closer look at this issue.

BTW, did you have a look at this page?
http://restlet.com/technical-resources/apispark/tutorials/document-restlet-api

It might help you as well as this GitHub project:
https://github.com/restlet/restlet-sample-descriptor

**Comment by boillodmanuel** [comment]
@komasoftware it's fixed 
(comment https://github.com/restlet/restlet-framework-java/issues/945#issuecomment-75887160)

Generics Type with variable is not supported, so for this kind of property, the property will be ignored and with the following message
`Could not add property list of representation SearchResult. Type java.util.List<D> is a generic type with unkwnown type. This is not supported.
`

**Comment by jlouvel** [comment]
@boillodmanuel Thanks for the update and fix.
I've added a RFE #1039

**Comment by jlouvel** [comment]
GAE edition of Restlet isn't necessary anymore and has been removed from 2.5 branch. GAE can now run any Java app
